FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache git

ENV PATH="/usr/local/go/bin:/go/bin:${PATH}"

COPY go.mod ./
RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@v1.49.0

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
